name: Feature Request
description: Sugiere una nueva funcionalidad o mejora
title: '[Feature] '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema oportunidad
      description: ¿Qué problema resuelve? ¿Qué falta?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solución propuesta
      description: Describe la funcionalidad o cambio deseado.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: ¿Qué alternativas has considerado?
    validations:
      required: false
